version: '3.8'

services:
  redis:
    image: redis:7.0.11

  redis-commander:
    image: rediscommander/redis-commander

    ports:
      - 8081:8081

    depends_on:
      - redis
    
    environment:
      REDIS_HOSTS: local:redis:6379
