version: '3.8'

volumes:
  maria_vol:
  
services:
  mariadb:
    
    image: mariadb:10.9.6

    volumes:
      - maria_vol:/data/db

    environment:
      MYSQL_ROOT_PASSWORD: senha123

  phpmyadmin:
    
    image: phpmyadmin:5.2.1
    
    ports:
      - 8080:80
    
    environment:
      - PMA_HOST=mariadb
